language: java
jdk: openjdk8
os: linux
dist: xenial

cache:
  directories:
    # Maven dependencies and wrappers
    - $HOME/.m2
    # TODO add gradle cache
before_cache:
  # ensure that we do not keep bonitasoft artifacts accross builds
  - rm -rf $HOME/.m2/repository/org/bonitasoft

branches:
  only:
  - master

script: ./build-script.sh
