language: java
jdk: openjdk8
os: linux
dist: xenial

cache:
  directories:
    # Maven dependencies and wrappers
    - $HOME/.m2
    # Gradle caches and wrapper
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


branches:
  only:
  - master
  - dev

env:
  global:
    - BONITA_BUILD_NO_CLEAN=true


jobs:
  include:
    - stage: build without studio
      before_cache:
        # Maven: ensure that we do not keep bonitasoft artifacts across builds
        # temp bonita dependencies must be available for studio
        #TODO store them in the cache but remove them prior building (in the before_script phase)
        #- rm -rf $HOME/.m2/repository/org/bonitasoft
        # Gradle: see https://docs.travis-ci.com/user/languages/java/#projects-using-gradle
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      before_script:
        - ls -lh $HOME/.m2
        # do not declare environment variables in the env section to ensure the cache is shared by jobs
        # see https://docs.travis-ci.com/user/caching/#caches-and-build-matrices
        - export BONITA_BUILD_QUIET=true
        - export BONITA_BUILD_STUDIO_SKIP=true
      script: ./build-script.sh
    - stage: build studio
    # see https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services
    services:
      - xvfb
    install:
        # openjdk11 should be installed
        # https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
        - /usr/local/lib/jvm/openjdk11/bin/java --version
        - export BONITA_BUILD_QUIET=false
        - export BONITA_BUILD_STUDIO_ONLY=true
        before_cache:
        # remove studio-only configuration
        - rm -f  $HOME/.m2/toolchains.xml
      before_script:
        # copy maven toolchains.xml configuration file
        - ls -lh $HOME/.m2
        - cp  .travis/maven/toolchains.xml $HOME/.m2/
        - ls -lh $HOME/.m2
      script: ./build-script.sh
