# TODO if this is working, see if we use a single file for both Mac and Windows
name: MacOS Build

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven configuration
      shell: bash
      run: |
        mkdir -p $HOME/.m2/
        ls -lah $HOME/.m2/
        cp $GITHUB_WORKSPACE/.github/workflows/maven/settings.xml $HOME/.m2/
        ls -lh $HOME/.m2/
    - name: Build
      shell: bash
      run: ./build-script.sh
#      run: echo "skipped for now, as we know it is working"
