# TODO if this is working, see if we use a single file for both Mac and Windows
name: MacOS Build

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven configuration
      shell: bash
      run: |
        mkdir -p $HOME/.m2/
        ls -lah $HOME/.m2/
        cp $GITHUB_WORKSPACE/.github/workflows/maven/settings.xml $HOME/.m2/
        ls -lh $HOME/.m2/
    - name: Build without Studio
      shell: bash
      run: ./build-script.sh
      env:
        BONITA_BUILD_STUDIO_SKIP: true
    - name: Prepare Bonita bundle for upload
      shell: bash
      run: |
        mkdir -p artifacts/bundle
        cp bonita-distrib/bundle/tomcat/target/*.zip artifacts/bundle/
        ls -lh artifacts/bundle/
    - name: Upload Bonita bundle
      uses: actions/upload-artifact@master
      with:
        name: bonita-bundle
        path: artifacts/bundle/
# TODO restore Studio build
#    - name: Build Studio
#      shell: bash
#      run: ./build-script.sh
#      env:
#        BONITA_BUILD_STUDIO_ONLY: true
# TODO upload Studio if possible
# from bonita-studio/all-in-one/target
