name: Windows Build

# see https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
on: [push, pull_request]
  branches:
    - master
    - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven configuration
      shell: bash
      run: |
        mkdir -p $HOME/.m2/
        ls -lah $HOME/.m2/
        cp $GITHUB_WORKSPACE/.github/workflows/maven/settings.xml $HOME/.m2/
        ls -lh $HOME/.m2/
    - name: Build
      shell: bash
      run: ./build-script.sh
# TODO give a try to the upload-artifact actions to store bundle and Studio
# see https://github.com/actions/upload-artifact
