name: Windows Build

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven configuration
      shell: bash
      run: |
        mkdir -p $HOME/.m2/
        ls -lah $HOME/.m2/
        cp $GITHUB_WORKSPACE/.github/workflows/maven/settings.xml $HOME/.m2/
        ls -lh $HOME/.m2/
    - name: Build without Studio
      shell: bash
      run: ./build-script.sh
      env:
        BONITA_BUILD_QUIET: true
        BONITA_BUILD_STUDIO_SKIP: true
    # TODO see if we can create an action that will hide this
    - name: Prepare Bonita bundle for upload
      shell: bash
      run: |
        mkdir -p artifacts/bundle
        cp bonita-distrib/bundle/tomcat/target/*.zip artifacts/bundle/
        ls -lh artifacts/bundle/
    - name: Upload Bonita bundle
      # see https://help.github.com/en/github/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts and https://github.com/actions/upload-artifact
      uses: actions/upload-artifact@master
      with:
        name: bonita-bundle
        path: artifacts/bundle/
    - name: Build Studio
      shell: bash
      run: ./build-script.sh
      env:
        BONITA_BUILD_QUIET: true
        BONITA_BUILD_STUDIO_ONLY: true
    - name: Prepare Bonita Studio for upload
      shell: bash
      run: |
        mkdir -p artifacts/studio
        cp bonita-studio/all-in-one/target/*.zip artifacts/studio/
        ls -lh artifacts/studio/
    - name: Upload Bonita Studio
      # see https://github.com/actions/upload-artifact
      uses: actions/upload-artifact@master
      with:
        name: bonita-studio
        path: artifacts/studio/
